### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Darkhax** [Team-Hollow/Deeper-Caverns#2] opened 2019-10-31 01:47 UTC
```
java.lang.NoSuchMethodError: net.minecraft.util.registry.MutableRegistry.func_212607_c(Lnet/minecraft/util/ResourceLocation;)Z
	at teamhollow.deepercaverns.world.dimension.DeeperCavernsDimensions$ForgeEvents.registerDimensions(DeeperCavernsDimensions.java:36) ~[?:0.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_29_ForgeEvents_registerDimensions_RegisterDimensionsEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.DimensionManager.fireRegister(DimensionManager.java:412) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:358) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:352) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
```

Forge 28.1.74
Caverns: 0.0.1

**Comment by Mahtaran** [comment] 2019-10-31 06:44
Caused by newer Forge mappings. Will update our mapping soon.

**Comment by Mahtaran** [comment] 2019-10-31 11:12
Never mind what I previously said, the method is client-side only. Will be fixed soon.

**Closed** 2019-10-31 16:05 UTC
Labels: bug
